"""
Category configuration — GENERATED by tools/sync_label_mapping.py.

DO NOT edit CATEGORY_CONFIG by hand. To modify:
  - Active classes / subs: edit /home/lgai/cv-project/code/label_mapping.py
    (KEEP_MAINS, ACTIVE_SUBS) and re-run:
        python tools/sync_label_mapping.py
  - DINO prompt aliases: edit KOR_TO_EN in label_mapping.py
  - CLIP sub descriptions: edit _ALL_CATEGORIES below, then re-run sync

Sub label normalization (matches CSV after 00_make_split): spaces removed,
"cm" -> "㎝".
"""
from __future__ import annotations

# Full 96-category universe. Sub-string values are CLIP prompts;
# sub_categories keys match normalized CSV sub labels.
_ALL_CATEGORIES: dict[str, dict] = {
    'TV장식장(거실장)': {
        "dino_prompt": 'tv stand . tv cabinet .',
        "sub_categories": {
            'TV장식장(거실장)_가로90㎝이상': 'a wide TV stand or media cabinet at least 90 centimeters wide',
            'TV장식장(거실장)_단순받침대': 'a simple flat TV base or stand without cabinet storage',
        },
    },
    '가방': {
        "dino_prompt": 'bag . luggage . suitcase .',
        "sub_categories": {
            '가방_골프가방': 'a golf bag for carrying golf clubs, long cylindrical shape',
            '가방_캐리어': 'a wheeled travel suitcase or luggage carrier',
        },
    },
    '거울(액자형)': {
        "dino_prompt": 'mirror .',
        "sub_categories": {
            '거울(액자형)_1㎡미만': 'a framed mirror less than 1 square meter in area',
            '거울(액자형)_1㎡이상': 'a large framed mirror at least 1 square meter in area',
        },
    },
    '공기청정기및가습기': {
        "dino_prompt": 'air purifier . humidifier . tower purifier .',
        "sub_categories": {
            '공기청정기및가습기_높이1m미만': 'an air purifier or humidifier less than 1 meter tall',
            '공기청정기및가습기_높이1m이상': 'a tall standing air purifier or humidifier at least 1 meter in height',
        },
    },
    '냉장고': {
        "dino_prompt": 'refrigerator . fridge .',
        "sub_categories": {
            '냉장고_300ℓ미만': 'a medium refrigerator between 100 and 300 liters capacity',
            '냉장고_300ℓ이상': 'a large refrigerator with capacity between 300 and 500 liters',
            '냉장고_500ℓ이상': 'a very large refrigerator with capacity of 500 liters or more',
        },
    },
    '상': {
        "dino_prompt": 'low table . korean floor table .',
        "sub_categories": {
            '상_4인용미만': 'a small low Korean dining table seating fewer than 4 people',
            '상_4인용이상': 'a large low Korean dining table seating 4 or more people',
        },
    },
    '선풍기': {
        "dino_prompt": 'electric fan .',
        "sub_categories": {
            '선풍기_모든규격': 'an electric fan of any size',
        },
    },
    '세면대(양변기)': {
        "dino_prompt": 'toilet .',
        "sub_categories": {
            '세면대(양변기)_모든규격': 'a bathroom sink or toilet bowl of any size',
        },
    },
    '세탁기': {
        "dino_prompt": 'washing machine .',
        "sub_categories": {
            '세탁기_8㎏이상': 'a large washing machine with capacity of 8 kilograms or more',
        },
    },
    '소파': {
        "dino_prompt": 'sofa . couch .',
        "sub_categories": {
            '소파_1인용': 'a small narrow single-seat armchair with armrests on both sides and a short seat width suitable for only one person',
            '소파_2인용': 'a medium-width two-seat sofa just wide enough for two adults, with two seat cushions and a compact frame',
            '소파_3인용이상': 'a very long wide sofa large enough to seat three or more adults side by side, with a broad frame and multiple seat cushions',
            '소파_카우치': 'an L-shaped sectional sofa or chaise lounge with one side extending into a long flat reclining section for legs',
            '소파_스툴,코너': 'an ottoman stool or corner sofa piece, a small seat without a back or a corner sectional sofa piece',
        },
    },
    '소화기': {
        "dino_prompt": 'fire extinguisher .',
        "sub_categories": {
            '소화기_3.5㎏이하(약제기준)': 'a small fire extinguisher with agent weight 3.5 kg or less',
            '소화기_3.5㎏초과(약제기준)': 'a large fire extinguisher with agent weight exceeding 3.5 kg',
        },
    },
    '시계': {
        "dino_prompt": 'clock . wall clock .',
        "sub_categories": {
            '시계_벽걸이용': 'a wall-mounted clock',
        },
    },
    '식탁': {
        "dino_prompt": 'dining table .',
        "sub_categories": {
            '식탁_4인용이상(일반)': 'a standard dining table seating 4 or more people',
        },
    },
    '실내조명등기구': {
        "dino_prompt": 'ceiling light . chandelier . pendant light .',
        "sub_categories": {
            '실내조명등기구_일반': 'a standard indoor light fixture or ceiling lamp',
            '실내조명등기구_장식용': 'a decorative indoor light fixture or ornamental lamp',
        },
    },
    '에어컨및온풍기': {
        "dino_prompt": 'air conditioner . wall ac unit .',
        "sub_categories": {
            '에어컨및온풍기_0.5㎡미만': 'an air conditioner or heater with face area under 0.5 square meters',
            '에어컨및온풍기_1.0㎡미만': 'an air conditioner or heater with face area between 0.5 and 1 square meters',
            '에어컨및온풍기_1.0㎡이상': 'a large air conditioner or heater with face area at least 1 square meter',
        },
    },
    '오락기': {
        "dino_prompt": 'arcade machine . game machine .',
        "sub_categories": {
            '오락기_소형': 'a small arcade or tabletop game machine',
        },
    },
    '옷걸이': {
        "dino_prompt": 'coat rack . clothes hanger stand .',
        "sub_categories": {
            '옷걸이_모든규격': 'a coat rack or standing clothes hanger of any size',
        },
    },
    '의료기': {
        "dino_prompt": 'medical device .',
        "sub_categories": {
            '의료기_일반': 'a standard medical device without stand',
        },
    },
    '의자': {
        "dino_prompt": 'chair . office chair . armchair .',
        "sub_categories": {
            '의자_보조,간이': 'a folding chair or auxiliary simple chair',
            '의자_사무용': 'an office chair with wheels and adjustable height',
            '의자_편의용(안락,흔들,식탁)': 'a comfortable lounge chair, rocking chair, or dining chair',
        },
    },
    '자전거': {
        "dino_prompt": 'bicycle .',
        "sub_categories": {
            '자전거_성인용': 'an adult bicycle',
            '자전거_아동용': "a children's bicycle",
        },
    },
    '전기밥솥': {
        "dino_prompt": 'rice cooker .',
        "sub_categories": {
            '전기밥솥_모든규격': 'an electric rice cooker of any size',
        },
    },
    '전자레인지': {
        "dino_prompt": 'microwave .',
        "sub_categories": {
            '전자레인지_모든규격': 'a microwave oven of any size',
        },
    },
    '진열장(장식장,책장,찬장)': {
        "dino_prompt": 'display cabinet . bookshelf . cupboard .',
        "sub_categories": {
            '진열장(장식장,책장,찬장)_가로90㎝미만': 'a narrow compact bookshelf or cabinet with a small horizontal width under 90 centimeters',
            '진열장(장식장,책장,찬장)_가로90㎝이상': 'a wide bookshelf or cabinet spanning a broad wall area, at least 90 centimeters wide',
        },
    },
    '책상': {
        "dino_prompt": 'desk . writing desk .',
        "sub_categories": {
            '책상_가로120㎝미만': 'a desk less than 120 centimeters wide',
        },
    },
    '청소기': {
        "dino_prompt": 'vacuum cleaner . upright vacuum .',
        "sub_categories": {
            '청소기_가정용(모든규격)': 'a household vacuum cleaner of any size',
            '청소기_업소용(모든규격)': 'a commercial or industrial vacuum cleaner of any size',
        },
    },
    '컴퓨터': {
        "dino_prompt": 'computer . desktop computer . monitor .',
        "sub_categories": {
            '컴퓨터_모니터': 'a computer monitor or display screen',
            '컴퓨터_본체': 'a desktop computer tower or PC unit',
        },
    },
    '텔레비전': {
        "dino_prompt": 'tv . television . flat screen tv .',
        "sub_categories": {
            '텔레비전_30인치미만': 'a medium television between 14 and 30 inches',
            '텔레비전_30인치이상': 'a large television 30 inches or larger',
        },
    },
    '프린트기': {
        "dino_prompt": 'printer .',
        "sub_categories": {
            '프린트기_업체용대형외모든규격': 'a standard household or office printer',
        },
    },
    '피아노': {
        "dino_prompt": 'piano .',
        "sub_categories": {
            '피아노_전자피아노,풍금': 'an electronic piano, digital piano, or organ',
        },
    },
    '형광등기구': {
        "dino_prompt": 'fluorescent light .',
        "sub_categories": {
            '형광등기구_길이1m미만': 'a fluorescent light fixture less than 1 meter long',
            '형광등기구_길이1m이상': 'a fluorescent light fixture at least 1 meter long',
        },
    },
    '화장대': {
        "dino_prompt": 'dressing table . vanity table .',
        "sub_categories": {
            '화장대_가로90㎝미만': 'a vanity dresser or dressing table less than 90 centimeters wide',
        },
    },
}

# Active main categories — derived from label_mapping.KEEP_MAINS
# (mains with at least one sub_category having CSV count >= 100).
ACTIVE_MAIN: set[str] = {
    'TV장식장(거실장)',
    '가방',
    '거울(액자형)',
    '공기청정기및가습기',
    '냉장고',
    '상',
    '선풍기',
    '세면대(양변기)',
    '세탁기',
    '소파',
    '소화기',
    '시계',
    '식탁',
    '실내조명등기구',
    '에어컨및온풍기',
    '오락기',
    '옷걸이',
    '의료기',
    '의자',
    '자전거',
    '전기밥솥',
    '전자레인지',
    '진열장(장식장,책장,찬장)',
    '책상',
    '청소기',
    '컴퓨터',
    '텔레비전',
    '프린트기',
    '피아노',
    '형광등기구',
    '화장대',
}

# Pipeline-facing config: active mains only.
# - dino_prompt: built from KOR_TO_EN aliases (label_mapping.py)
# - sub_categories: from _ALL_CATEGORIES, filtered to ACTIVE_SUBS
CATEGORY_CONFIG: dict[str, dict] = {
    'TV장식장(거실장)': {
        "dino_prompt": 'tv stand . tv cabinet .',
        "sub_categories": {
            'TV장식장(거실장)_가로90㎝이상': 'a wide TV stand or media cabinet at least 90 centimeters wide',
            'TV장식장(거실장)_단순받침대': 'a simple flat TV base or stand without cabinet storage',
        },
    },
    '가방': {
        "dino_prompt": 'bag . luggage . suitcase .',
        "sub_categories": {
            '가방_골프가방': 'a golf bag for carrying golf clubs, long cylindrical shape',
            '가방_캐리어': 'a wheeled travel suitcase or luggage carrier',
        },
    },
    '거울(액자형)': {
        "dino_prompt": 'mirror .',
        "sub_categories": {
            '거울(액자형)_1㎡미만': 'a framed mirror less than 1 square meter in area',
            '거울(액자형)_1㎡이상': 'a large framed mirror at least 1 square meter in area',
        },
    },
    '공기청정기및가습기': {
        "dino_prompt": 'air purifier . humidifier . tower purifier .',
        "sub_categories": {
            '공기청정기및가습기_높이1m미만': 'an air purifier or humidifier less than 1 meter tall',
            '공기청정기및가습기_높이1m이상': 'a tall standing air purifier or humidifier at least 1 meter in height',
        },
    },
    '냉장고': {
        "dino_prompt": 'refrigerator . fridge .',
        "sub_categories": {
            '냉장고_300ℓ미만': 'a medium refrigerator between 100 and 300 liters capacity',
            '냉장고_300ℓ이상': 'a large refrigerator with capacity between 300 and 500 liters',
            '냉장고_500ℓ이상': 'a very large refrigerator with capacity of 500 liters or more',
        },
    },
    '상': {
        "dino_prompt": 'low table . korean floor table .',
        "sub_categories": {
            '상_4인용미만': 'a small low Korean dining table seating fewer than 4 people',
            '상_4인용이상': 'a large low Korean dining table seating 4 or more people',
        },
    },
    '선풍기': {
        "dino_prompt": 'electric fan .',
        "sub_categories": {
            '선풍기_모든규격': 'an electric fan of any size',
        },
    },
    '세면대(양변기)': {
        "dino_prompt": 'toilet .',
        "sub_categories": {
            '세면대(양변기)_모든규격': 'a bathroom sink or toilet bowl of any size',
        },
    },
    '세탁기': {
        "dino_prompt": 'washing machine .',
        "sub_categories": {
            '세탁기_8㎏이상': 'a large washing machine with capacity of 8 kilograms or more',
        },
    },
    '소파': {
        "dino_prompt": 'sofa . couch .',
        "sub_categories": {
            '소파_1인용': 'a small narrow single-seat armchair with armrests on both sides and a short seat width suitable for only one person',
            '소파_2인용': 'a medium-width two-seat sofa just wide enough for two adults, with two seat cushions and a compact frame',
            '소파_3인용이상': 'a very long wide sofa large enough to seat three or more adults side by side, with a broad frame and multiple seat cushions',
            '소파_카우치': 'an L-shaped sectional sofa or chaise lounge with one side extending into a long flat reclining section for legs',
            '소파_스툴,코너': 'an ottoman stool or corner sofa piece, a small seat without a back or a corner sectional sofa piece',
        },
    },
    '소화기': {
        "dino_prompt": 'fire extinguisher .',
        "sub_categories": {
            '소화기_3.5㎏이하(약제기준)': 'a small fire extinguisher with agent weight 3.5 kg or less',
            '소화기_3.5㎏초과(약제기준)': 'a large fire extinguisher with agent weight exceeding 3.5 kg',
        },
    },
    '시계': {
        "dino_prompt": 'clock . wall clock .',
        "sub_categories": {
            '시계_벽걸이용': 'a wall-mounted clock',
        },
    },
    '식탁': {
        "dino_prompt": 'dining table .',
        "sub_categories": {
            '식탁_4인용이상(일반)': 'a standard dining table seating 4 or more people',
        },
    },
    '실내조명등기구': {
        "dino_prompt": 'ceiling light . chandelier . pendant light .',
        "sub_categories": {
            '실내조명등기구_일반': 'a standard indoor light fixture or ceiling lamp',
            '실내조명등기구_장식용': 'a decorative indoor light fixture or ornamental lamp',
        },
    },
    '에어컨및온풍기': {
        "dino_prompt": 'air conditioner . wall ac unit .',
        "sub_categories": {
            '에어컨및온풍기_0.5㎡미만': 'an air conditioner or heater with face area under 0.5 square meters',
            '에어컨및온풍기_1.0㎡미만': 'an air conditioner or heater with face area between 0.5 and 1 square meters',
            '에어컨및온풍기_1.0㎡이상': 'a large air conditioner or heater with face area at least 1 square meter',
        },
    },
    '오락기': {
        "dino_prompt": 'arcade machine . game machine .',
        "sub_categories": {
            '오락기_소형': 'a small arcade or tabletop game machine',
        },
    },
    '옷걸이': {
        "dino_prompt": 'coat rack . clothes hanger stand .',
        "sub_categories": {
            '옷걸이_모든규격': 'a coat rack or standing clothes hanger of any size',
        },
    },
    '의료기': {
        "dino_prompt": 'medical device .',
        "sub_categories": {
            '의료기_일반': 'a standard medical device without stand',
        },
    },
    '의자': {
        "dino_prompt": 'chair . office chair . armchair .',
        "sub_categories": {
            '의자_보조,간이': 'a folding chair or auxiliary simple chair',
            '의자_사무용': 'an office chair with wheels and adjustable height',
            '의자_편의용(안락,흔들,식탁)': 'a comfortable lounge chair, rocking chair, or dining chair',
        },
    },
    '자전거': {
        "dino_prompt": 'bicycle .',
        "sub_categories": {
            '자전거_성인용': 'an adult bicycle',
            '자전거_아동용': "a children's bicycle",
        },
    },
    '전기밥솥': {
        "dino_prompt": 'rice cooker .',
        "sub_categories": {
            '전기밥솥_모든규격': 'an electric rice cooker of any size',
        },
    },
    '전자레인지': {
        "dino_prompt": 'microwave .',
        "sub_categories": {
            '전자레인지_모든규격': 'a microwave oven of any size',
        },
    },
    '진열장(장식장,책장,찬장)': {
        "dino_prompt": 'display cabinet . bookshelf . cupboard .',
        "sub_categories": {
            '진열장(장식장,책장,찬장)_가로90㎝미만': 'a narrow compact bookshelf or cabinet with a small horizontal width under 90 centimeters',
            '진열장(장식장,책장,찬장)_가로90㎝이상': 'a wide bookshelf or cabinet spanning a broad wall area, at least 90 centimeters wide',
        },
    },
    '책상': {
        "dino_prompt": 'desk . writing desk .',
        "sub_categories": {
            '책상_가로120㎝미만': 'a desk less than 120 centimeters wide',
        },
    },
    '청소기': {
        "dino_prompt": 'vacuum cleaner . upright vacuum .',
        "sub_categories": {
            '청소기_가정용(모든규격)': 'a household vacuum cleaner of any size',
            '청소기_업소용(모든규격)': 'a commercial or industrial vacuum cleaner of any size',
        },
    },
    '컴퓨터': {
        "dino_prompt": 'computer . desktop computer . monitor .',
        "sub_categories": {
            '컴퓨터_모니터': 'a computer monitor or display screen',
            '컴퓨터_본체': 'a desktop computer tower or PC unit',
        },
    },
    '텔레비전': {
        "dino_prompt": 'tv . television . flat screen tv .',
        "sub_categories": {
            '텔레비전_30인치미만': 'a medium television between 14 and 30 inches',
            '텔레비전_30인치이상': 'a large television 30 inches or larger',
        },
    },
    '프린트기': {
        "dino_prompt": 'printer .',
        "sub_categories": {
            '프린트기_업체용대형외모든규격': 'a standard household or office printer',
        },
    },
    '피아노': {
        "dino_prompt": 'piano .',
        "sub_categories": {
            '피아노_전자피아노,풍금': 'an electronic piano, digital piano, or organ',
        },
    },
    '형광등기구': {
        "dino_prompt": 'fluorescent light .',
        "sub_categories": {
            '형광등기구_길이1m미만': 'a fluorescent light fixture less than 1 meter long',
            '형광등기구_길이1m이상': 'a fluorescent light fixture at least 1 meter long',
        },
    },
    '화장대': {
        "dino_prompt": 'dressing table . vanity table .',
        "sub_categories": {
            '화장대_가로90㎝미만': 'a vanity dresser or dressing table less than 90 centimeters wide',
        },
    },
}
