"""
Sync ~/cv-project/code/label_mapping.py -> ~/cv-project-semi/config.py.

Inputs
------
  /home/lgai/cv-project/code/label_mapping.py
    KOR_TO_EN     : dict[main_kor, list[en_alias]]   (DINO prompt source)
    ACTIVE_SUBS   : set[sub_label]                   (CSV count >= 100)
    KEEP_MAINS    : set[main_kor]                    (active mains)

  ./config.py (semi)
    CATEGORY_CONFIG with 2 active + 94 commented entries — sub descriptions
    (CLIP-friendly natural language) live here.

Output (overwrites ./config.py)
-------------------------------
  _ALL_CATEGORIES : full 96-category universe (descriptions preserved)
  ACTIVE_MAIN     : KEEP_MAINS (single source of truth)
  CATEGORY_CONFIG : active subset
                    - dino_prompt overridden by KOR_TO_EN aliases
                    - sub_categories filtered to ACTIVE_SUBS (normalized)

Run:
    python tools/sync_label_mapping.py
    python tools/sync_label_mapping.py --dry-run    # print to stdout
"""
from __future__ import annotations

import argparse
import ast
import importlib.util
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SEMI_CONFIG = REPO_ROOT / "config.py"
DEFAULT_LABEL_MAPPING = REPO_ROOT / "src" / "label_mapping.py"


def normalize_sub(s: str) -> str:
    """Match semi's sub_category normalization: spaces removed, 'cm' -> '㎝'."""
    return s.replace(" ", "").replace("cm", "㎝")


def import_label_mapping(path: Path):
    spec = importlib.util.spec_from_file_location("_label_mapping_src", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load module from {path}")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _uncomment_dict_members(src: str) -> str:
    """Strip leading "# " only on commented dict-structure lines.

    A line qualifies if, after removing "# ", it starts with a dict-syntax
    char (string quote, brace, paren, comma). Plain prose comments like
    "# Uncomment to include additional categories:" are left intact, otherwise
    they would unfold into invalid Python.
    """
    out: list[str] = []
    struct_chars = ('"', "'", "{", "}", "(", ")", ",")
    for line in src.splitlines(keepends=True):
        m = re.match(r"^(\s+)#\s?(.*)$", line, flags=re.DOTALL)
        if m:
            indent, rest = m.group(1), m.group(2)
            stripped = rest.lstrip()
            if stripped and stripped[0] in struct_chars:
                out.append(indent + rest)
                continue
        out.append(line)
    return "".join(out)


def _find_dict_assign(tree: ast.Module, name: str):
    for node in tree.body:
        target_id = None
        value = None
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target_id = node.target.id
            value = node.value
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 \
                and isinstance(node.targets[0], ast.Name):
            target_id = node.targets[0].id
            value = node.value
        if target_id == name and value is not None:
            return value
    return None


def parse_all_categories(src: str) -> dict[str, dict]:
    """Parse config.py and return the 96-category universe.

    Lookup order (so re-runs preserve all descriptions):
      1. _ALL_CATEGORIES   — present in regenerated configs (idempotent path)
      2. CATEGORY_CONFIG   — fallback for the first run against semi's
                             original config (96 entries, mostly commented out)
    """
    uncommented = _uncomment_dict_members(src)
    try:
        tree = ast.parse(uncommented)
    except SyntaxError as e:
        lines = uncommented.splitlines()
        lo, hi = max(0, e.lineno - 4), min(len(lines), e.lineno + 3)
        ctx = "\n".join(f"{i+1:4d}: {lines[i]}" for i in range(lo, hi))
        raise RuntimeError(
            f"ast.parse failed at line {e.lineno}: {e.msg}\n"
            f"context:\n{ctx}"
        ) from e

    for name in ("_ALL_CATEGORIES", "CATEGORY_CONFIG"):
        value = _find_dict_assign(tree, name)
        if value is not None:
            return ast.literal_eval(value)
    raise RuntimeError(
        "Neither _ALL_CATEGORIES nor CATEGORY_CONFIG found in config.py"
    )


def build_dino_prompt(aliases: list[str]) -> str:
    parts = [a.lower().strip() for a in aliases if a and a.strip()]
    return " . ".join(parts) + " ."


HEADER = '''"""
Category configuration — GENERATED by tools/sync_label_mapping.py.

DO NOT edit CATEGORY_CONFIG by hand. To modify:
  - Active classes / subs: edit /home/lgai/cv-project/code/label_mapping.py
    (KEEP_MAINS, ACTIVE_SUBS) and re-run:
        python tools/sync_label_mapping.py
  - DINO prompt aliases: edit KOR_TO_EN in label_mapping.py
  - CLIP sub descriptions: edit _ALL_CATEGORIES below, then re-run sync

Sub label normalization (matches CSV after 00_make_split): spaces removed,
"cm" -> "㎝".
"""
from __future__ import annotations

'''


def _emit_dict_block(name: str, type_hint: str, items: dict[str, dict]) -> list[str]:
    lines = [f"{name}: {type_hint} = {{\n"]
    for main, entry in items.items():
        lines.append(f"    {main!r}: {{\n")
        lines.append(f'        "dino_prompt": {entry["dino_prompt"]!r},\n')
        lines.append('        "sub_categories": {\n')
        for sk, sv in entry["sub_categories"].items():
            lines.append(f"            {sk!r}: {sv!r},\n")
        lines.append("        },\n")
        lines.append("    },\n")
    lines.append("}\n\n")
    return lines


def render(
    all_categories: dict[str, dict],
    active_main: set[str],
    kor_to_en: dict[str, list[str]],
    active_subs_norm: set[str],
) -> tuple[str, list[str]]:
    out: list[str] = [HEADER]

    out.append("# Full 96-category universe. Sub-string values are CLIP prompts;\n")
    out.append("# sub_categories keys match normalized CSV sub labels.\n")
    out.extend(_emit_dict_block("_ALL_CATEGORIES", "dict[str, dict]", all_categories))

    out.append("# Active main categories — derived from label_mapping.KEEP_MAINS\n")
    out.append("# (mains with at least one sub_category having CSV count >= 100).\n")
    out.append("ACTIVE_MAIN: set[str] = {\n")
    for m in sorted(active_main):
        out.append(f"    {m!r},\n")
    out.append("}\n\n")

    out.append("# Pipeline-facing config: active mains only.\n")
    out.append("# - dino_prompt: built from KOR_TO_EN aliases (label_mapping.py)\n")
    out.append("# - sub_categories: from _ALL_CATEGORIES, filtered to ACTIVE_SUBS\n")
    out.append("CATEGORY_CONFIG: dict[str, dict] = {\n")
    skipped: list[str] = []
    for main in sorted(active_main):
        if main not in all_categories:
            skipped.append(f"{main}: missing from _ALL_CATEGORIES (add a description block)")
            continue
        entry = all_categories[main]
        new_prompt = build_dino_prompt(kor_to_en.get(main, [main.lower()]))
        filtered = {
            sk: sv
            for sk, sv in entry["sub_categories"].items()
            if sk in active_subs_norm
        }
        if not filtered:
            skipped.append(f"{main}: no sub_categories match ACTIVE_SUBS")
            continue
        out.append(f"    {main!r}: {{\n")
        out.append(f'        "dino_prompt": {new_prompt!r},\n')
        out.append('        "sub_categories": {\n')
        for sk, sv in filtered.items():
            out.append(f"            {sk!r}: {sv!r},\n")
        out.append("        },\n")
        out.append("    },\n")
    out.append("}\n")
    return "".join(out), skipped


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--label-mapping", type=Path, default=DEFAULT_LABEL_MAPPING)
    ap.add_argument("--config", type=Path, default=SEMI_CONFIG)
    ap.add_argument("--out", type=Path, default=SEMI_CONFIG)
    ap.add_argument("--dry-run", action="store_true",
                    help="print rendered config to stdout instead of writing")
    args = ap.parse_args()

    if not args.label_mapping.exists():
        print(f"[error] label_mapping not found: {args.label_mapping}", file=sys.stderr)
        return 1
    if not args.config.exists():
        print(f"[error] semi config not found: {args.config}", file=sys.stderr)
        return 1

    lm = import_label_mapping(args.label_mapping)
    KOR_TO_EN = lm.KOR_TO_EN
    ACTIVE_SUBS = lm.ACTIVE_SUBS
    KEEP_MAINS = lm.KEEP_MAINS
    print(
        f"[info] label_mapping: {len(KOR_TO_EN)} mains total, "
        f"{len(KEEP_MAINS)} active mains, {len(ACTIVE_SUBS)} active subs",
        file=sys.stderr,
    )

    src = args.config.read_text(encoding="utf-8")
    all_cats = parse_all_categories(src)
    print(f"[info] semi config parsed: {len(all_cats)} categories", file=sys.stderr)

    active_subs_norm = {normalize_sub(s) for s in ACTIVE_SUBS}

    semi_subs: set[str] = set()
    for entry in all_cats.values():
        semi_subs.update(entry["sub_categories"].keys())
    missing = sorted(active_subs_norm - semi_subs)
    if missing:
        print(
            f"[warn] {len(missing)} active subs have no description in _ALL_CATEGORIES:",
            file=sys.stderr,
        )
        for s in missing:
            print(f"    {s}", file=sys.stderr)
        print(
            "    -> these subs will be omitted from CATEGORY_CONFIG until added.",
            file=sys.stderr,
        )

    rendered, skipped = render(all_cats, KEEP_MAINS, KOR_TO_EN, active_subs_norm)

    if skipped:
        print(f"[warn] {len(skipped)} active mains skipped:", file=sys.stderr)
        for s in skipped:
            print(f"    {s}", file=sys.stderr)

    if args.dry_run:
        sys.stdout.write(rendered)
        return 0

    args.out.write_text(rendered, encoding="utf-8")
    n_written = rendered.count('"dino_prompt"') - len(all_cats)
    print(f"[done] wrote {args.out}", file=sys.stderr)
    print(
        f"[summary] _ALL_CATEGORIES={len(all_cats)}, "
        f"ACTIVE_MAIN={len(KEEP_MAINS)}, CATEGORY_CONFIG entries={n_written}",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
